sonar.cpd.exclusions=workers/index.mjs, workers/index.js
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=*
sonar.issue.ignore.multicriteria.e1.resourceKey=workers/index.mjs
