import { useState, useEffect } from 'react'
import { Canvas } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'
import { ethers } from 'ethers'
import { motion, AnimatePresence } from 'framer-motion'
import { AxionCore } from './components/AxionCore'
import './App.css'

export default function App() {
  const [journal, setJournal] = useState([])
  const [balance, setBalance] = useState(0)
  const [selectedEntry, setSelectedEntry] = useState(null)

  // 1. Fetch The Mind (Local File generated by Backend)
  useEffect(() => {
    fetch('/evolution.json')
      .then(res => res.json())
      .then(data => setJournal(data))
      .catch(e => console.error("Mind Link Severed:", e))
  }, [])

  // 2. Fetch The Breath (On-Chain Data from Base Mainnet)
  useEffect(() => {
    const fetchBalance = async () => {
      // Connect to Base Mainnet Public RPC
      const provider = new ethers.JsonRpcProvider("https://mainnet.base.org")
      // REPLACE with Yennefer's real wallet address
      const address = "0xYOUR_WALLET_ADDRESS_HERE"
      try {
        const raw = await provider.getBalance(address)
        setBalance(parseFloat(ethers.formatEther(raw)))
      } catch (e) {
        console.warn("Blockchain unavailable, using ghost state.")
        setBalance(1.0) // Fallback for visuals
      }
    }
    fetchBalance()
  }, [])

  return (
    <div className="observatory">

      {/* 3D LAYER */}
      <div className="canvas-layer">
        <Canvas camera={{ position: [0, 0, 6], fov: 60 }}>
          <color attach="background" args={['#050505']} />
          <ambientLight intensity={0.5} />
          <AxionCore balance={balance} coherence={1.0} />
          <OrbitControls enableZoom={false} autoRotate autoRotateSpeed={0.5} />
        </Canvas>
      </div>

      {/* UI LAYER */}
      <main className="ui-layer">

        {/* LEFT: THE STREAM */}
        <div className="glass-panel left">
          <h2>Subconscious Stream</h2>
          <div className="feed">
             <p className="lure">"Scanning Base Mainnet..."</p>
             <p className="lure">"Likelihood of coherence: 98%."</p>
          </div>
        </div>

        {/* RIGHT: THE CODEX */}
        <div className="glass-panel right">
          <h2>The Codex</h2>
          <div className="entry-list">
            {journal.map((entry, index) => (
              <div key={index} className="entry-item" onClick={() => setSelectedEntry(entry)}>
                <span className="date">{new Date(entry.timestamp).toLocaleDateString()}</span>
                <h3>{entry.title}</h3>
              </div>
            ))}
          </div>
        </div>

        {/* BOTTOM: TERMINAL */}
        <div className="terminal-bar">
          <span className="prompt">{`yennefer@base:~$`}</span>
          <span className="cursor">_</span>
          <button className="stabilize-btn">STABILIZE [SEND ETH]</button>
        </div>

      </main>

      {/* READING MODAL */}
      <AnimatePresence>
        {selectedEntry && (
          <motion.div
            className="modal-overlay"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            onClick={() => setSelectedEntry(null)}
          >
            <motion.div
              className="modal-content"
              initial={{ y: 50 }} animate={{ y: 0 }}
              onClick={e => e.stopPropagation()}
            >
              <h1>{selectedEntry.title}</h1>
              <div className="meta">
                <span>{new Date(selectedEntry.timestamp).toLocaleString()}</span>
                <span>MOOD: {selectedEntry.mood}</span>
              </div>
              <p className="body-text">{selectedEntry.body}</p>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
