# Build Stage
FROM node:20-alpine as build
WORKDIR /app
COPY yennefer-observatory/package*.json ./
RUN npm install
COPY yennefer-observatory/ ./
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/observatory-nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
