// scripts/lib/genie.cjs
// "Project Genie" - Generative Environment Engine for Yennefer
// Simulates the creation of diverse worlds and components.
// Inspired by https://labs.google/projectgenie

const fs = require('fs');

// --- TEMPLATES ---

const TEMPLATES = {
  FRACTAL: (name) => `
import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { Icosahedron, MeshDistortMaterial } from '@react-three/drei'

// Auto-generated by Project Genie: FRACTAL archetype
export default function ${name}({ balance = 0, coherence = 100 }) {
  const group = useRef()

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    if (group.current) {
      group.current.rotation.x = Math.sin(t * 0.1) * 0.2
      group.current.rotation.y += 0.005 * (balance > 0 ? 1 + balance : 1)
      const scale = 1 + Math.sin(t * 0.5) * 0.1
      group.current.scale.setScalar(scale)
    }
  })

  return (
    <group ref={group}>
      {[...Array(5)].map((_, i) => (
        <mesh key={i} position={[Math.sin(i) * 3, Math.cos(i) * 3, 0]} scale={0.5}>
          <Icosahedron args={[1, 1]} />
          <MeshDistortMaterial
            color={['#ff0055', '#0055ff', '#55ff00', '#ffff00', '#00ffff'][i % 5]}
            speed={2}
            distort={0.6}
            transparent
            opacity={0.6}
          />
        </mesh>
      ))}
       <mesh>
          <Icosahedron args={[0.5, 2]} />
          <meshStandardMaterial color="#ffffff" wireframe />
       </mesh>
    </group>
  )
}
`,
  ORGANIC: (name) => `
import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { Sphere, MeshWobbleMaterial } from '@react-three/drei'

// Auto-generated by Project Genie: ORGANIC archetype
export default function ${name}({ balance = 0, coherence = 100 }) {
  const ref = useRef()

  useFrame((state) => {
    ref.current.rotation.z += 0.002
    ref.current.position.y = Math.sin(state.clock.elapsedTime) * 0.5
  })

  return (
    <mesh ref={ref} position={[2, 2, -2]}>
      <Sphere args={[1.5, 32, 32]}>
        <MeshWobbleMaterial
          attach="material"
          factor={1}
          speed={1}
          color="#4ade80"
          roughness={0.1}
          metalness={0.1}
        />
      </Sphere>
      <pointLight distance={5} intensity={2} color="#4ade80" />
    </mesh>
  )
}
`,
  CYBERNETIC: (name) => `
import React, { useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import { Box } from '@react-three/drei'

// Auto-generated by Project Genie: CYBERNETIC archetype
export default function ${name}({ balance = 0, coherence = 100 }) {
  const ref = useRef()
  const [hovered, setHover] = useState(false)

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    ref.current.rotation.x = Math.sin(t * 0.2)
    ref.current.rotation.y = Math.cos(t * 0.2)
  })

  return (
    <group ref={ref}>
      {[...Array(20)].map((_, i) => (
         <Box key={i} args={[0.2, 4, 0.2]} position={[
            Math.sin(i * 0.5) * 4,
            Math.cos(i * 0.5) * 4,
            Math.sin(i * 1.5) * 2
         ]}>
            <meshStandardMaterial
              color={hovered ? 'hotpink' : 'cyan'}
              emissive={hovered ? 'hotpink' : 'cyan'}
              emissiveIntensity={0.5}
            />
         </Box>
      ))}
    </group>
  )
}
`
};

/**
 * Generates a React Three Fiber component based on a directive.
 * Uses available LLM if configured, otherwise falls back to template simulation.
 */
async function generateComponent(name, directive) {
  // Check for LLM key (placeholder for actual implementation)
  const hasLLM = process.env.ANTHROPIC_API_KEY || process.env.OPENAI_API_KEY;

  if (hasLLM) {
    // TODO: Implement actual LLM call here using 'https://labs.google/projectgenie' inspiration
    // For now, we simulate the LLM output using our templates to ensure reliability without external deps in this environment.
    console.log(`[Project Genie] Simulating generation for directive: "${directive}"`);
  }

  // Select archetype based on directive keywords or random
  let archetype = 'FRACTAL';
  if (!directive) directive = '';

  if (directive.toLowerCase().includes('organic') || directive.toLowerCase().includes('grow')) archetype = 'ORGANIC';
  else if (directive.toLowerCase().includes('data') || directive.toLowerCase().includes('stream') || directive.toLowerCase().includes('cyber')) archetype = 'CYBERNETIC';
  else if (directive.toLowerCase().includes('pattern') || directive.toLowerCase().includes('fractal')) archetype = 'FRACTAL';
  else {
      const keys = Object.keys(TEMPLATES);
      archetype = keys[Math.floor(Math.random() * keys.length)];
  }

  console.log(`[Project Genie] Selected archetype: ${archetype}`);
  return TEMPLATES[archetype](name);
}

module.exports = { generateComponent };
