// scripts/lib/genie.cjs
// Yennefer "Project Genie" Simulation Engine
// Generates infinitely diverse worlds (React Three Fiber components)
// based on directives from the Visionary.

// In the future, this will integrate with:
// https://labs.google/projectgenie

const GEOMETRIES = [
  'boxGeometry',
  'sphereGeometry',
  'coneGeometry',
  'cylinderGeometry',
  'torusGeometry',
  'torusKnotGeometry',
  'dodecahedronGeometry',
  'icosahedronGeometry',
  'octahedronGeometry'
];

const MATERIALS = [
  'meshStandardMaterial',
  'meshNormalMaterial',
  'meshPhongMaterial',
  'meshPhysicalMaterial',
  // Drei materials
  'MeshDistortMaterial',
  'MeshWobbleMaterial'
];

function getRandomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateRandomColor() {
  return '#' + Math.floor(Math.random()*16777215).toString(16).padStart(6, '0');
}

function generateEvolutionComponent(name, directive) {
  const geometry = getRandomElement(GEOMETRIES);
  const material = getRandomElement(MATERIALS);
  const color1 = generateRandomColor();
  const color2 = generateRandomColor();
  const distort = (Math.random() * 0.5 + 0.1).toFixed(2);
  const speed = (Math.random() * 2 + 0.5).toFixed(2);

  // Basic prompt analysis to influence generation
  let scaleBase = 1;
  if (directive.toLowerCase().includes("expand") || directive.toLowerCase().includes("grow")) {
    scaleBase = 1.5;
  }

  const isDreiMaterial = material[0] === 'M'; // Drei materials start with Uppercase in our list

  // Build imports
  let dreiImports = [];
  if (isDreiMaterial) {
    dreiImports.push(material);
  }

  return `// Auto-generated by Yennefer Genie Engine
// Directive: ${directive}
// Generated: ${new Date().toISOString()}

import React, { useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import { ${dreiImports.join(', ')} } from '@react-three/drei'
import * as THREE from 'three'

export default function ${name}({ balance = 0, coherence = 100 }) {
  const meshRef = useRef()
  const [hovered, setHover] = useState(false)

  // Random seed for this instance
  const seed = useRef(Math.random())
  const initialPos = useRef([
    (Math.random() - 0.5) * 4,
    (Math.random() - 0.5) * 4,
    (Math.random() - 0.5) * 2
  ])

  useFrame((state) => {
    if (meshRef.current) {
      // Rotate based on time and coherence
      const t = state.clock.elapsedTime
      meshRef.current.rotation.x = Math.sin(t * ${speed} * 0.5) + seed.current
      meshRef.current.rotation.y += 0.01 * (coherence / 50)

      // Pulse based on balance
      const scale = ${scaleBase} + Math.sin(t * 2) * (balance * 0.05) + (hovered ? 0.2 : 0)
      meshRef.current.scale.setScalar(scale)
    }
  })

  return (
    <group>
      <mesh
        ref={meshRef}
        position={initialPos.current}
        onPointerOver={() => setHover(true)}
        onPointerOut={() => setHover(false)}
      >
        <${geometry} args={[1, ${geometry.includes('torus') ? '0.4, 64, 32' : ''}]} />
        <${material}
          color="${color1}"
          ${isDreiMaterial ? `distort={${distort}} speed={${speed}}` : ''}
          ${material === 'meshStandardMaterial' ? `emissive="${color2}" emissiveIntensity={0.5}` : ''}
          ${material === 'meshPhysicalMaterial' ? `transmission={0.6} roughness={0.2}` : ''}
          wireframe={${Math.random() > 0.8}}
        />
      </mesh>
    </group>
  )
}
`;
}

module.exports = { generateEvolutionComponent };
