// scripts/lib/genie.cjs
// Project Genie: Generative World Module for Yennefer Observatory
// Simulates "infinite diversity" by procedurally combining geometries, materials, and animations.

function generateWorldComponent(directive) {
  const componentName = directive.replace(/[^a-zA-Z]/g, '').slice(0, 20) || 'GenieCreation';

  // Random selection helpers
  const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
  const randomFloat = (min, max) => Math.random() * (max - min) + min;

  // Configuration Palettes
  // Using intrinsic geometry elements for flexibility
  const GEOMETRIES = [
    { type: 'boxGeometry', args: '[1, 1, 1]' },
    { type: 'sphereGeometry', args: '[1, 32, 32]' },
    { type: 'torusGeometry', args: '[1, 0.4, 16, 100]' },
    { type: 'torusKnotGeometry', args: '[1, 0.3, 100, 16]' },
    { type: 'dodecahedronGeometry', args: '[1, 0]' },
    { type: 'icosahedronGeometry', args: '[1, 0]' },
    { type: 'octahedronGeometry', args: '[1, 0]' }
  ];

  // Materials can be intrinsic or from Drei
  const MATERIALS = [
    { type: 'meshStandardMaterial', props: '', isDrei: false },
    { type: 'MeshDistortMaterial', props: 'distort={0.4} speed={2}', isDrei: true },
    { type: 'MeshWobbleMaterial', props: 'factor={1} speed={2}', isDrei: true },
    { type: 'meshPhongMaterial', props: 'shininess={100}', isDrei: false }
  ];

  const COLORS = [
    '#050505', // Void Black
    '#4ade80', // Neon Green
    '#8b5cf6', // Violet
    '#ec4899', // Pink
    '#06b6d4', // Cyan
    '#f59e0b', // Amber
    '#10b981', // Emerald
    '#6366f1'  // Indigo
  ];

  // Procedural Choices
  const geometry = pick(GEOMETRIES);
  const material = pick(MATERIALS);
  const color = pick(COLORS);
  const emissive = pick(COLORS);

  // Animation Logic (randomized)
  const animationType = pick(['ROTATE', 'FLOAT', 'PULSE', 'WOBBLE']);
  let animationCode = '';

  switch (animationType) {
    case 'ROTATE':
      animationCode = `
      meshRef.current.rotation.x += ${randomFloat(0.001, 0.01)}
      meshRef.current.rotation.y += ${randomFloat(0.001, 0.01)}
      `;
      break;
    case 'FLOAT':
      animationCode = `
      meshRef.current.position.y = Math.sin(state.clock.elapsedTime * ${randomFloat(0.5, 2)}) * ${randomFloat(0.2, 1)}
      meshRef.current.rotation.y += 0.005
      `;
      break;
    case 'PULSE':
      animationCode = `
      const scale = 1 + Math.sin(state.clock.elapsedTime * ${randomFloat(1, 3)}) * 0.2
      meshRef.current.scale.setScalar(scale * (1 + balance * 0.1))
      meshRef.current.rotation.z += 0.002
      `;
      break;
    case 'WOBBLE':
      animationCode = `
      meshRef.current.rotation.x = Math.sin(state.clock.elapsedTime) * 0.2
      meshRef.current.rotation.z = Math.cos(state.clock.elapsedTime) * 0.2
      `;
      break;
  }

  // Generate Component Code
  // Only import used Drei components
  const dreiImports = [];
  if (material.isDrei) dreiImports.push(material.type);

  const importStatement = dreiImports.length > 0
    ? `import { ${dreiImports.join(', ')} } from '@react-three/drei'`
    : `// No extra imports needed`;

  return `// Auto-generated by Project Genie Integration
// Directive: ${directive}
// Generated: ${new Date().toISOString()}

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
${importStatement}

export default function ${componentName}({ balance = 0, coherence = 100 }) {
  const meshRef = useRef()

  useFrame((state) => {
    if (meshRef.current) {
      ${animationCode}
    }
  })

  const materialProps = {
    color: "${color}",
    emissive: "${emissive}",
    emissiveIntensity: 0.5 + (balance * 0.5),
    roughness: ${randomFloat(0.1, 0.5)},
    metalness: ${randomFloat(0.5, 0.9)},
    wireframe: ${Math.random() > 0.8}
  }

  return (
    <mesh ref={meshRef} position={[${randomFloat(-5, 5)}, ${randomFloat(-3, 3)}, ${randomFloat(-5, 5)}]}>
      <${geometry.type} args={${geometry.args}} />
      <${material.type}
        {...materialProps}
        ${material.props}
      />
    </mesh>
  )
}
`;
}

module.exports = { generateWorldComponent };
