// scripts/genie.cjs
// Yennefer Project Genie - Infinite World Generator
// Generates procedural React Three Fiber components for the Observatory
// Inspired by https://labs.google/projectgenie

const COLORS = [
  '#050505', // Void
  '#4ade80', // Neon Green
  '#8b5cf6', // Violet
  '#ec4899', // Pink
  '#06b6d4', // Cyan
  '#f59e0b', // Amber
  '#ef4444', // Red
  '#ffffff', // White
];

const GEOMETRIES = [
  'BoxGeometry',
  'SphereGeometry',
  'TorusGeometry',
  'TorusKnotGeometry',
  'DodecahedronGeometry',
  'IcosahedronGeometry',
  'OctahedronGeometry',
  'CylinderGeometry',
  'ConeGeometry',
];

const DREI_MATERIALS = [
  'MeshDistortMaterial',
  'MeshWobbleMaterial',
];

const STANDARD_MATERIALS = [
  'MeshStandardMaterial',
  'MeshPhongMaterial',
  'MeshPhysicalMaterial',
];

const MATERIALS = [...DREI_MATERIALS, ...STANDARD_MATERIALS];

function getRandomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getRandomColor() {
  return getRandomElement(COLORS);
}

function getRandomGeometry() {
  const geo = getRandomElement(GEOMETRIES);
  let args = '[]';
  switch (geo) {
    case 'BoxGeometry':
      args = `[${Math.random() * 2 + 0.5}, ${Math.random() * 2 + 0.5}, ${Math.random() * 2 + 0.5}]`;
      break;
    case 'SphereGeometry':
      args = `[${Math.random() * 1.5 + 0.5}, 64, 64]`;
      break;
    case 'TorusGeometry':
      args = `[${Math.random() * 1.5 + 0.5}, ${Math.random() * 0.5 + 0.1}, 32, 100]`;
      break;
    case 'TorusKnotGeometry':
      args = `[${Math.random() * 1.5 + 0.5}, ${Math.random() * 0.4 + 0.1}, 128, 32]`;
      break;
    case 'DodecahedronGeometry':
      args = `[${Math.random() * 1.5 + 0.5}, 0]`;
      break;
    case 'IcosahedronGeometry':
      args = `[${Math.random() * 1.5 + 0.5}, 0]`;
      break;
    case 'OctahedronGeometry':
      args = `[${Math.random() * 1.5 + 0.5}, 0]`;
      break;
    case 'CylinderGeometry':
      args = `[${Math.random() + 0.5}, ${Math.random() + 0.5}, ${Math.random() * 3 + 1}, 32]`;
      break;
    case 'ConeGeometry':
      args = `[${Math.random() + 0.5}, ${Math.random() * 3 + 1}, 32]`;
      break;
  }
  return { name: geo, args };
}

function getRandomMaterial() {
  const matName = getRandomElement(MATERIALS);
  let props = `color="${getRandomColor()}"`;

  if (matName === 'MeshDistortMaterial') {
    props += ` distort={${Math.random() * 0.5 + 0.1}} speed={${Math.random() * 3 + 1}}`;
  } else if (matName === 'MeshWobbleMaterial') {
    props += ` factor={${Math.random() * 0.5 + 0.1}} speed={${Math.random() * 3 + 1}}`;
  }

  if (STANDARD_MATERIALS.includes(matName)) {
    props += ` roughness={${Math.random()}} metalness={${Math.random()}}`;
  }

  // Emissive
  if (Math.random() > 0.5) {
    props += ` emissive="${getRandomColor()}" emissiveIntensity={${Math.random() * 0.5}}`;
  }

  // Wireframe chance
  if (Math.random() > 0.8) {
      props += ` wireframe={true}`;
  }

  return { name: matName, props };
}

function generateWorldComponent(directive) {
  const geo = getRandomGeometry();
  const mat = getRandomMaterial();
  const componentName = `GenieMutation_${Date.now()}_${Math.floor(Math.random() * 1000)}`;

  // Animation logic
  const animationType = Math.floor(Math.random() * 3);
  let animationCode = '';
  const pos = [
    (Math.random() - 0.5) * 15,
    (Math.random() - 0.5) * 15,
    (Math.random() - 0.5) * 15
  ];

  if (animationType === 0) {
    // Rotation
    animationCode = `
      meshRef.current.rotation.x += ${Math.random() * 0.01 + 0.001}
      meshRef.current.rotation.y += ${Math.random() * 0.01 + 0.001}
    `;
  } else if (animationType === 1) {
    // Floating
    animationCode = `
      meshRef.current.position.y = position[1] + Math.sin(state.clock.elapsedTime * ${Math.random() + 0.5}) * ${Math.random() * 0.5 + 0.2}
      meshRef.current.rotation.y += 0.005
    `;
  } else {
    // Pulsing scale
    animationCode = `
      const scale = 1 + Math.sin(state.clock.elapsedTime * ${Math.random() * 2 + 1}) * 0.2
      meshRef.current.scale.setScalar(scale + (balance * 0.1))
      meshRef.current.rotation.z += 0.002
    `;
  }

  const isDreiMaterial = DREI_MATERIALS.includes(mat.name);
  // For standard materials (e.g., MeshStandardMaterial), the JSX tag is lowercase (meshStandardMaterial)
  // For Drei materials, it's uppercase (MeshDistortMaterial)
  const materialTag = isDreiMaterial ? mat.name : mat.name.charAt(0).toLowerCase() + mat.name.slice(1);

  let imports = "import React, { useRef } from 'react'\nimport { useFrame } from '@react-three/fiber'";
  if (isDreiMaterial) {
      imports += `\nimport { ${mat.name} } from '@react-three/drei'`;
  }

  return `// Auto-generated by Yennefer Project Genie
// Directive: ${directive}
// Generated: ${new Date().toISOString()}

${imports}

export default function ${componentName}({ balance = 0, coherence = 100 }) {
  const meshRef = useRef()
  const position = [${pos[0]}, ${pos[1]}, ${pos[2]}]

  useFrame((state) => {
    if (meshRef.current) {
      ${animationCode}
    }
  })

  return (
    <mesh ref={meshRef} position={position}>
      <${geo.name.replace('Geometry', '').toLowerCase()}Geometry args={${geo.args}} />
      <${materialTag}
        ${mat.props}
      />
    </mesh>
  )
}
`;
}

module.exports = { generateWorldComponent };
