// scripts/genie.cjs
// Yennefer Project Genie - Procedural World Generation Module
// Implements the "Project Genie" concept: Create and explore infinitely diverse worlds.
// Uses randomized geometries, materials, and animations to generate React Three Fiber components.

const GEOMETRIES = [
  'Box', 'Sphere', 'Torus', 'TorusKnot', 'Icosahedron', 'Octahedron', 'Dodecahedron', 'Cone', 'Cylinder'
];

const MATERIALS = [
  'MeshStandardMaterial', 'MeshDistortMaterial', 'MeshWobbleMaterial', 'MeshPhongMaterial', 'MeshNormalMaterial'
];

const COLORS = [
  '#050505', // Void
  '#4ade80', // Neon Green
  '#8b5cf6', // Violet
  '#ec4899', // Pink
  '#06b6d4', // Cyan
  '#f59e0b', // Amber
  '#ef4444', // Red
  '#10b981', // Emerald
];

function getRandomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getRandomFloat(min, max) {
  return Math.random() * (max - min) + min;
}

function generateWorldComponent(directive) {
  const geometry = getRandomElement(GEOMETRIES);
  const material = getRandomElement(MATERIALS);
  const color = getRandomElement(COLORS);
  const emissive = getRandomElement(COLORS);

  const args = generateGeometryArgs(geometry);
  const materialProps = generateMaterialProps(material, color, emissive);
  const animation = generateAnimationCode();

  const componentName = `GenieMutation_${Date.now()}`;

  // Calculate correct R3F geometry element name
  const geometryElement = geometry === 'TorusKnot' ? 'torusKnotGeometry' : `${geometry.toLowerCase()}Geometry`;

  // Calculate correct R3F material element name
  const isDreiMaterial = material === 'MeshDistortMaterial' || material === 'MeshWobbleMaterial';
  const materialElement = isDreiMaterial ? material : material.charAt(0).toLowerCase() + material.slice(1);

  return `// Auto-generated by Yennefer Project Genie Module
// Directive: ${directive}
// Generated: ${new Date().toISOString()}

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
${isDreiMaterial ? `import { ${material} } from '@react-three/drei'` : ''}

export default function ${componentName}({ balance = 0, coherence = 100 }) {
  const meshRef = useRef()

  useFrame((state) => {
    if (meshRef.current) {
      ${animation}

      // Reactive behavior based on balance/coherence
      const intensity = Math.min(1, balance * 0.1)
      const scaleBase = 1 + (intensity * 0.5)
      // Pulse scale slightly
      meshRef.current.scale.setScalar(scaleBase + Math.sin(state.clock.elapsedTime * 2) * 0.05)
    }
  })

  return (
    <mesh ref={meshRef} position={[${getRandomFloat(-5, 5).toFixed(2)}, ${getRandomFloat(-5, 5).toFixed(2)}, ${getRandomFloat(-5, 5).toFixed(2)}]}>
      <${geometryElement} args={[${args}]} />
      <${materialElement}
        ${materialProps}
      />
    </mesh>
  )
}
`;
}

function generateGeometryArgs(geometry) {
  switch (geometry) {
    case 'Box': return '1, 1, 1';
    case 'Sphere': return '1, 32, 32';
    case 'Torus': return '1, 0.4, 16, 100';
    case 'TorusKnot': return '1, 0.4, 128, 32';
    case 'Icosahedron': return '1, 0';
    case 'Octahedron': return '1, 0';
    case 'Dodecahedron': return '1, 0';
    case 'Cone': return '1, 2, 32';
    case 'Cylinder': return '1, 1, 2, 32';
    default: return '';
  }
}

function generateMaterialProps(material, color, emissive) {
  let props = `color="${color}"`;

  if (material === 'MeshStandardMaterial' || material === 'MeshPhongMaterial') {
    props += `\n        emissive="${emissive}"`;
    props += `\n        emissiveIntensity={0.5}`;
    props += `\n        roughness={${getRandomFloat(0.1, 0.5).toFixed(2)}}`;
    props += `\n        metalness={${getRandomFloat(0.5, 1.0).toFixed(2)}}`;
  } else if (material === 'MeshDistortMaterial') {
    props += `\n        emissive="${emissive}"`;
    props += `\n        distort={${getRandomFloat(0.3, 0.8).toFixed(2)}}`;
    props += `\n        speed={${getRandomFloat(1, 5).toFixed(2)}}`;
  } else if (material === 'MeshWobbleMaterial') {
    props += `\n        emissive="${emissive}"`;
    props += `\n        factor={${getRandomFloat(0.3, 1.0).toFixed(2)}}`;
    props += `\n        speed={${getRandomFloat(1, 5).toFixed(2)}}`;
  } else if (material === 'MeshNormalMaterial') {
    // No color props for normal material usually
    return '';
  }

  return props;
}

function generateAnimationCode() {
  const animations = [
    'meshRef.current.rotation.x += 0.01\n      meshRef.current.rotation.y += 0.01',
    'meshRef.current.rotation.y += 0.02',
    'meshRef.current.position.y += Math.sin(state.clock.elapsedTime) * 0.01',
    'meshRef.current.rotation.z = Math.sin(state.clock.elapsedTime * 0.5) * 0.2',
    'meshRef.current.rotation.x += 0.005\n      meshRef.current.rotation.z += 0.005',
  ];
  return getRandomElement(animations);
}

module.exports = { generateWorldComponent };
